rvm:
  - 1.9.2
  - 1.9.3
before_install:
  - sudo apt-get install wget git
  - sudo gem install spawn
  - sudo easy_install virtualenv
  - sudo easy_install tornado
  - sudo easy_install nltk
  - sudo easy_install nose
  - ./scripts/set_test_env
  - perl ~/src/taxon-finder/server.pl nohup
  - python ~/src/neti_neti/neti_tornado_server.py nohup
bundler_args: --without development
branches:
  only:
      - master
