rvm:
  - 1.9.3
before_install:
  - sudo apt-get install wget git
  - sudo gem install spawn
  - sudo easy_install virtualenv
  - sudo easy_install tornado
  - sudo easy_install nltk
  - sudo easy_install nose
  - ./scripts/set_test_env
  - nohup python ./src/neti_neti/neti_tornado_server.py
  - nohup perl ./src/taxon-finder/server.pl
bundler_args: --without development
branches:
  only:
      - master
