rvm:
  - 2.0
  - 2.1
  - 2.2
bundler_args: --without development
before_install:
  - sudo apt-get install wget git
  - sudo easy_install virtualenv
  - sudo easy_install tornado
  - sudo easy_install nltk
  - sudo easy_install nose
before_script:
  - ./scripts/set_travis_env
  - cd src/taxon-finder
  - perl server.pl &
  - cd ../..
  - python ./src/neti_neti/neti_tornado_server.py &
  - sleep 100
branches:
  only:
      - master
